id = "pluto"
name = "Pluto Language Support"
version = "0.1.0"
schema_version = 1
authors = ["s7g4"]
description = "A lightweight, expressive syntax for scripting with full syntax highlighting and parsing support for Zed using Tree-sitter"
repository = "https://github.com/s7g4/zed-pluto"

[grammars.pluto]
path = "languages/pluto/tree-sitter-pluto"